"""submission ordinal

Revision ID: a3fc9e83b1fe
Revises: aa2a5177007a
Create Date: 2026-07-29 09:19:24.154609

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'a3fc9e83b1fe'
down_revision: str | None = 'aa2a5177007a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('ordinal', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_submissions_session_id'), 'submissions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_session_id'), table_name='submissions')
    op.drop_column('submissions', 'ordinal')
    # ### end Alembic commands ###
