"""adaptive difficulty tracking columns

Revision ID: 94be5129dfb8
Revises: 4eaa7716b3fa
Create Date: 2026-07-28 21:49:11.733938

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '94be5129dfb8'
down_revision: str | None = '4eaa7716b3fa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('current_difficulty', sa.Float(), nullable=True))
    op.add_column('exam_sessions', sa.Column('current_difficulty_band', sa.String(length=16), nullable=True))
    op.add_column('session_questions', sa.Column('shown_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_questions', 'shown_at')
    op.drop_column('exam_sessions', 'current_difficulty_band')
    op.drop_column('exam_sessions', 'current_difficulty')
    # ### end Alembic commands ###
