"""hiring report columns

Revision ID: 8a76103f402f
Revises: a3fc9e83b1fe
Create Date: 2026-07-29 10:50:20.261451

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8a76103f402f'
down_revision: str | None = 'a3fc9e83b1fe'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('hiring_report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exam_sessions', sa.Column('hiring_report_recommendation', sa.String(length=16), nullable=True))
    op.add_column('exam_sessions', sa.Column('hiring_report_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('exams', sa.Column('candidate_profile_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'candidate_profile_id')
    op.drop_column('exam_sessions', 'hiring_report_generated_at')
    op.drop_column('exam_sessions', 'hiring_report_recommendation')
    op.drop_column('exam_sessions', 'hiring_report_json')
    # ### end Alembic commands ###
