"""submissions and case verdicts

Revision ID: 2b742992e15e
Revises: 7e80bc66cec2
Create Date: 2026-07-21 14:21:52.382970

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2b742992e15e'
down_revision: str | None = '7e80bc66cec2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('question_version_id', sa.Uuid(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('compare_mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary_verdict', sa.String(length=4), nullable=True),
    sa.Column('compile_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_submissions_exam_id_exams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions'))
    )
    op.create_index(op.f('ix_submissions_exam_id'), 'submissions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_submissions_org_id'), 'submissions', ['org_id'], unique=False)
    op.create_table('case_verdicts',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=4), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=False),
    sa.Column('memory_kb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_case_verdicts_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_verdicts')),
    sa.UniqueConstraint('submission_id', 'ordinal', name=op.f('uq_case_verdicts_submission_id'))
    )
    op.create_index(op.f('ix_case_verdicts_org_id'), 'case_verdicts', ['org_id'], unique=False)
    op.create_index(op.f('ix_case_verdicts_submission_id'), 'case_verdicts', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_verdicts_submission_id'), table_name='case_verdicts')
    op.drop_index(op.f('ix_case_verdicts_org_id'), table_name='case_verdicts')
    op.drop_table('case_verdicts')
    op.drop_index(op.f('ix_submissions_org_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_exam_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
