"""mode 2 slot questions

Revision ID: 4eaa7716b3fa
Revises: 38c6fd1cee57
Create Date: 2026-07-28 15:55:50.717838

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


revision: str = '4eaa7716b3fa'
down_revision: str | None = '38c6fd1cee57'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-written: exam_status is a native Postgres enum (see
    # app/models/exam.py), so autogenerate cannot detect new members — it
    # only diffs tables/columns/constraints, never enum value sets. New
    # values for Mode 2 profile-driven scheduling (Phase 2 Slice 4).
    op.execute("ALTER TYPE exam_status ADD VALUE IF NOT EXISTS 'pending_generation'")
    op.execute("ALTER TYPE exam_status ADD VALUE IF NOT EXISTS 'pending_review'")
    op.execute("ALTER TYPE exam_status ADD VALUE IF NOT EXISTS 'generation_failed'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_slot_questions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.Column('difficulty_band', sa.String(length=20), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=True),
    sa.Column('question_version_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_slot_questions_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_slot_questions')),
    sa.UniqueConstraint('exam_id', 'ordinal', name=op.f('uq_exam_slot_questions_exam_id'))
    )
    op.create_index(op.f('ix_exam_slot_questions_exam_id'), 'exam_slot_questions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_slot_questions_org_id'), 'exam_slot_questions', ['org_id'], unique=False)
    op.add_column('exams', sa.Column('review_deadline_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column(
        'exams',
        sa.Column('language_targets', postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'language_targets')
    op.drop_column('exams', 'review_deadline_at')
    op.drop_index(op.f('ix_exam_slot_questions_org_id'), table_name='exam_slot_questions')
    op.drop_index(op.f('ix_exam_slot_questions_exam_id'), table_name='exam_slot_questions')
    op.drop_table('exam_slot_questions')
    # ### end Alembic commands ###
    # Postgres cannot drop individual enum values (would require rebuilding
    # the type and rewriting every dependent column) — the three added
    # values are left in place on downgrade.
