"""blueprints

Revision ID: 643ab8c9d6bb
Revises: 1e8f10c987be
Create Date: 2026-07-20 18:21:02.788334

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '643ab8c9d6bb'
down_revision: str | None = '1e8f10c987be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprints'))
    )
    op.create_index(op.f('ix_blueprints_org_id'), 'blueprints', ['org_id'], unique=False)
    op.create_table('blueprint_versions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=120), nullable=False),
    sa.Column('experience_band', sa.String(length=60), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('topic_mix', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], name=op.f('fk_blueprint_versions_blueprint_id_blueprints'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blueprint_versions')),
    sa.UniqueConstraint('blueprint_id', 'version_number', name=op.f('uq_blueprint_versions_blueprint_id'))
    )
    op.create_index(op.f('ix_blueprint_versions_blueprint_id'), 'blueprint_versions', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_blueprint_versions_org_id'), 'blueprint_versions', ['org_id'], unique=False)
    # Circular FK pair (blueprints <-> blueprint_versions): added after both
    # tables exist.
    op.create_foreign_key(
        op.f('fk_blueprints_current_version_id_blueprint_versions'),
        'blueprints', 'blueprint_versions', ['current_version_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_blueprints_current_version_id_blueprint_versions'), 'blueprints', type_='foreignkey')
    op.drop_index(op.f('ix_blueprint_versions_org_id'), table_name='blueprint_versions')
    op.drop_index(op.f('ix_blueprint_versions_blueprint_id'), table_name='blueprint_versions')
    op.drop_table('blueprint_versions')
    op.drop_index(op.f('ix_blueprints_org_id'), table_name='blueprints')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
