"""exams and invites

Revision ID: 7e80bc66cec2
Revises: 643ab8c9d6bb
Create Date: 2026-07-20 22:05:04.055005

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7e80bc66cec2'
down_revision: str | None = '643ab8c9d6bb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_id', sa.Uuid(), nullable=False),
    sa.Column('blueprint_version_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_email', sa.String(length=320), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'in_progress', 'submitted', 'expired', 'cancelled', name='exam_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], name=op.f('fk_exams_blueprint_id_blueprints')),
    sa.ForeignKeyConstraint(['blueprint_version_id'], ['blueprint_versions.id'], name=op.f('fk_exams_blueprint_version_id_blueprint_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exams'))
    )
    op.create_index(op.f('ix_exams_candidate_email'), 'exams', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_exams_org_id'), 'exams', ['org_id'], unique=False)
    op.create_table('invites',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('candidate_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.Enum('pending', 'consumed', 'revoked', name='invite_status'), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_invites_exam_id_exams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('jti', name=op.f('uq_invites_jti'))
    )
    op.create_index(op.f('ix_invites_exam_id'), 'invites', ['exam_id'], unique=False)
    op.create_index(op.f('ix_invites_org_id'), 'invites', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invites_org_id'), table_name='invites')
    op.drop_index(op.f('ix_invites_exam_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_exams_org_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_candidate_email'), table_name='exams')
    op.drop_table('exams')
    sa.Enum(name='invite_status').drop(op.get_bind())
    sa.Enum(name='exam_status').drop(op.get_bind())
    # ### end Alembic commands ###
