"""orgs, examiners, refresh tokens

Revision ID: 1e8f10c987be
Revises: 13cb37e2451e
Create Date: 2026-07-19 22:10:07.162036

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '1e8f10c987be'
down_revision: str | None = '13cb37e2451e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgs'))
    )
    op.create_table('examiners',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'author', 'proctor', 'reviewer', name='examiner_role'), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_examiners_org_id_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_examiners')),
    sa.UniqueConstraint('email', name=op.f('uq_examiners_email'))
    )
    op.create_index(op.f('ix_examiners_org_id'), 'examiners', ['org_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('examiner_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['examiner_id'], ['examiners.id'], name=op.f('fk_refresh_tokens_examiner_id_examiners')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_refresh_tokens_org_id_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_examiner_id'), 'refresh_tokens', ['examiner_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_org_id'), 'refresh_tokens', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_tokens_org_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_examiner_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_examiners_org_id'), table_name='examiners')
    op.drop_table('examiners')
    op.drop_table('orgs')
    sa.Enum(name='examiner_role').drop(op.get_bind())
    # ### end Alembic commands ###
