"""submission run mode

Revision ID: 38c6fd1cee57
Revises: 7243a00888e2
Create Date: 2026-07-21 21:13:11.442946

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '38c6fd1cee57'
down_revision: str | None = '7243a00888e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills rows that predate the run/submit distinction.
    op.add_column(
        'submissions',
        sa.Column('mode', sa.String(length=8), nullable=False, server_default='submit'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'mode')
    # ### end Alembic commands ###
