"""exam sessions and assigned questions

Revision ID: 7243a00888e2
Revises: 2b742992e15e
Create Date: 2026-07-21 15:54:49.753388

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '7243a00888e2'
down_revision: str | None = '2b742992e15e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_sessions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('exam_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_email', sa.String(length=320), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('fk_exam_sessions_exam_id_exams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_sessions')),
    sa.UniqueConstraint('exam_id', name=op.f('uq_exam_sessions_exam_id'))
    )
    op.create_index(op.f('ix_exam_sessions_org_id'), 'exam_sessions', ['org_id'], unique=False)
    op.create_table('session_questions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('question_version_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], name=op.f('fk_session_questions_session_id_exam_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_questions')),
    sa.UniqueConstraint('session_id', 'ordinal', name=op.f('uq_session_questions_session_id'))
    )
    op.create_index(op.f('ix_session_questions_org_id'), 'session_questions', ['org_id'], unique=False)
    op.create_index(op.f('ix_session_questions_session_id'), 'session_questions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_questions_session_id'), table_name='session_questions')
    op.drop_index(op.f('ix_session_questions_org_id'), table_name='session_questions')
    op.drop_table('session_questions')
    op.drop_index(op.f('ix_exam_sessions_org_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    # ### end Alembic commands ###
