"""taxonomy, questions, versions, test cases

Revision ID: d68ae2dd781b
Revises: 
Create Date: 2026-07-20 11:34:31.354076

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd68ae2dd781b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'archived', name='question_status'), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.Column('published_version_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_org_id'), 'questions', ['org_id'], unique=False)
    op.create_table('topics',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['topics.id'], name=op.f('fk_topics_parent_id_topics')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('org_id', 'parent_id', 'name', name=op.f('uq_topics_org_id'), postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_topics_org_id'), 'topics', ['org_id'], unique=False)
    op.create_table('question_topics',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('topic_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_topics_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], name=op.f('fk_question_topics_topic_id_topics')),
    sa.PrimaryKeyConstraint('question_id', 'topic_id', name=op.f('pk_question_topics'))
    )
    op.create_table('question_versions',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('statement_md', sa.String(), nullable=False),
    sa.Column('constraints_md', sa.String(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('time_limit_ms', sa.Integer(), nullable=False),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=False),
    sa.Column('starter_code', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name=op.f('ck_question_versions_difficulty_range')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_question_versions_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_versions')),
    sa.UniqueConstraint('question_id', 'version_number', name=op.f('uq_question_versions_question_id'))
    )
    op.create_index(op.f('ix_question_versions_org_id'), 'question_versions', ['org_id'], unique=False)
    op.create_index(op.f('ix_question_versions_question_id'), 'question_versions', ['question_id'], unique=False)
    op.create_table('test_cases',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('question_version_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('input_s3_key', sa.String(length=512), nullable=False),
    sa.Column('expected_output_s3_key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], name=op.f('fk_test_cases_question_version_id_question_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_cases')),
    sa.UniqueConstraint('question_version_id', 'ordinal', name=op.f('uq_test_cases_question_version_id'))
    )
    op.create_index(op.f('ix_test_cases_org_id'), 'test_cases', ['org_id'], unique=False)
    op.create_index(op.f('ix_test_cases_question_version_id'), 'test_cases', ['question_version_id'], unique=False)
    # Circular FK pair (questions <-> question_versions): added after both
    # tables exist.
    op.create_foreign_key(
        op.f('fk_questions_current_version_id_question_versions'),
        'questions', 'question_versions', ['current_version_id'], ['id'],
    )
    op.create_foreign_key(
        op.f('fk_questions_published_version_id_question_versions'),
        'questions', 'question_versions', ['published_version_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_questions_current_version_id_question_versions'), 'questions', type_='foreignkey')
    op.drop_constraint(op.f('fk_questions_published_version_id_question_versions'), 'questions', type_='foreignkey')
    op.drop_index(op.f('ix_test_cases_question_version_id'), table_name='test_cases')
    op.drop_index(op.f('ix_test_cases_org_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_index(op.f('ix_question_versions_question_id'), table_name='question_versions')
    op.drop_index(op.f('ix_question_versions_org_id'), table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_table('question_topics')
    op.drop_index(op.f('ix_topics_org_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_questions_org_id'), table_name='questions')
    op.drop_table('questions')
    sa.Enum(name='question_status').drop(op.get_bind())
    # ### end Alembic commands ###
