"""test case generation jobs

Revision ID: 18d7b623e20a
Revises: 00a9d896537a
Create Date: 2026-07-28 14:47:58.333311

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '18d7b623e20a'
down_revision: str | None = '00a9d896537a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_case_generation_jobs',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('question_version_id', sa.Uuid(), nullable=False),
    sa.Column('generation_job_id', sa.Uuid(), nullable=False),
    sa.Column('synchronous', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('kept_case_count', sa.Integer(), nullable=False),
    sa.Column('discard_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_case_generation_jobs'))
    )
    op.create_index(op.f('ix_test_case_generation_jobs_org_id'), 'test_case_generation_jobs', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_generation_jobs_org_id'), table_name='test_case_generation_jobs')
    op.drop_table('test_case_generation_jobs')
    # ### end Alembic commands ###
