"""hiring reports

Revision ID: 96d8cee6448f
Revises: 3d64eb5d61c8
Create Date: 2026-07-29 10:55:49.180399

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '96d8cee6448f'
down_revision: str | None = '3d64eb5d61c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hiring_reports',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('report_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hiring_reports'))
    )
    op.create_index(op.f('ix_hiring_reports_org_id'), 'hiring_reports', ['org_id'], unique=False)
    op.create_index(op.f('ix_hiring_reports_session_id'), 'hiring_reports', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hiring_reports_session_id'), table_name='hiring_reports')
    op.drop_index(op.f('ix_hiring_reports_org_id'), table_name='hiring_reports')
    op.drop_table('hiring_reports')
    # ### end Alembic commands ###
