"""candidate profiles

Revision ID: 0c9ccf3345e5
Revises: 
Create Date: 2026-07-27 12:17:36.700163

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0c9ccf3345e5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resume_s3_key', sa.String(length=512), nullable=False),
    sa.Column('github_handle', sa.String(length=200), nullable=True),
    sa.Column('years_exp', sa.Integer(), nullable=True),
    sa.Column('domains', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('seniority_estimate', sa.String(length=50), nullable=True),
    sa.Column('weak_signals', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('strong_signals', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_profiles'))
    )
    op.create_index(op.f('ix_candidate_profiles_org_id'), 'candidate_profiles', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_profiles_org_id'), table_name='candidate_profiles')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
