"""session evaluations

Revision ID: 3d64eb5d61c8
Revises: 18d7b623e20a
Create Date: 2026-07-29 09:26:33.964831

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '3d64eb5d61c8'
down_revision: str | None = '18d7b623e20a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_evaluations',
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('question_version_id', sa.Uuid(), nullable=False),
    sa.Column('complexity', sa.String(length=20), nullable=True),
    sa.Column('approach', sa.String(length=64), nullable=True),
    sa.Column('partial_score', sa.Float(), nullable=False),
    sa.Column('behavioural_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_evaluations')),
    sa.UniqueConstraint('session_id', 'ordinal', name=op.f('uq_session_evaluations_session_id'))
    )
    op.create_index(op.f('ix_session_evaluations_org_id'), 'session_evaluations', ['org_id'], unique=False)
    op.create_index(op.f('ix_session_evaluations_session_id'), 'session_evaluations', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_evaluations_session_id'), table_name='session_evaluations')
    op.drop_index(op.f('ix_session_evaluations_org_id'), table_name='session_evaluations')
    op.drop_table('session_evaluations')
    # ### end Alembic commands ###
